# Generated by Django 3.2.5 on 2021-08-31 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Posts'},
        ),
    ]
