# Generated by Django 3.2.5 on 2021-09-08 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_posts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='posts/photo'),
            preserve_default=False,
        ),
    ]
