# Generated by Django 3.2.5 on 2021-09-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='user',
            new_name='post',
        ),
    ]
