# Generated by Django 3.2.5 on 2021-09-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210916_1912'),
        ('posts', '0009_alter_likes_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes_count',
            field=models.ManyToManyField(related_name='likes_count', to='user.Profile'),
        ),
    ]
