# Generated by Django 3.2.5 on 2021-09-30 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20210928_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes_users',
            field=models.ManyToManyField(related_name='likes_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
