# Generated by Django 3.2.5 on 2021-09-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_likes_likes_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
