# Generated by Django 3.2.5 on 2021-09-30 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_posts_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes_users',
            field=models.ManyToManyField(related_name='likes_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
