# Generated by Django 3.2.5 on 2021-09-17 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followers',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
