# Generated by Django 3.1.1 on 2021-10-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
